### ISSUE TITLE
parsing Orca 5.0.x outputs

### ISSUE THREAD

**Issue by Kr0n0ss** [eljost/thermoanalysis#5]
Hi,

Is the package currently able to parse the latest Orca 5.0.x outputs?

Thanks

**Comment by eljost** [comment]
I just added a custom parser for ORCA 5.0.x, as the cclib-support for 5.0.x is not yet available.
You can try it out. Let me know if it works for you or if something goes wrong.

**Comment by Kr0n0ss** [comment]
many thanks!

**Comment by Kr0n0ss** [comment]
stupid question, how do I add the new parser? I cloned and installed the package just now but I get a parsing error

**Comment by eljost** [comment]
Unless you want to program a parser by yourself you don't have to add any parser. If you provide me with the logfile I can check where things go wrong. If the file is somehow confidential you can also send it via email (found [here](https://github.com/eljost/thermoanalysis/blob/master/setup.cfg)).

**Comment by Kr0n0ss** [comment]
[orca.inp.log](https://github.com/eljost/thermoanalysis/files/8342665/orca.inp.log)

**Comment by eljost** [comment]
I think so. This is what I tested it with.

**Comment by Kr0n0ss** [comment]
Ok, many thanks!!!!

**Comment by rafaelpap** [comment]
Maybe it's better to use the .hess file from ORCA than the .log one?

**Comment by Kr0n0ss** [comment]
Ok. did not know it can also read  .hess

**Comment by rafaelpap** [comment]
> Ok. did not know it can also read .hess

Sorry for the confusion. I meant that instead of parsing the .log file it could be easiest to parse the .hess. There the geometry, frequencies, etc are in sync.

**Comment by Kr0n0ss** [comment]
I keep getting the same parsing error that I attached before. btw, I git clone https://github.com/eljost/thermoanalysis.git
again and reinstalled to account for any changes you might have done.
Not sure if that is the right way to go...

**Comment by eljost** [comment]
> Sorry for the confusion. I meant that instead of parsing the .log file it could be easiest to parse the .hess. There the geometry, frequencies, etc are in sync.

This is a good idea. I already have code for parsing the `.hess` file in my other project, `pysisyphus`.

**Comment by eljost** [comment]
I just added the `--mult` flag to specify a multiplicity for ORCA *.hess-files.
